[package]
name = "soil_sensor_common"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
defmt = ["dep:defmt"]
std = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = { version = "0.3", optional = true }