version: "3"

services:
  soil_sensor_postgres:
    image: postgres:15
    container_name: soil_sensor_postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    environment:
      POSTGRES_PASSWORD: "pleasedontstealmypassword"
    ports:
      - "5432:5432"
    user: 1000:1000
